// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficForm.Adapter;

#nullable disable

namespace TrafficForm.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    [Migration("20260323104847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficForm.Domain.CoordinateFavorite", b =>
                {
                    b.Property<string>("FavoriteId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FavoriteId");

                    b.ToTable("CoordinateFavorites");
                });

            modelBuilder.Entity("TrafficForm.Domain.HighwayFavorite", b =>
                {
                    b.Property<string>("FavoriteId")
                        .HasColumnType("text");

                    b.Property<int>("HighwayNo")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FavoriteId");

                    b.ToTable("HighwayFavorites");
                });

            modelBuilder.Entity("TrafficForm.Domain.CoordinateFavorite", b =>
                {
                    b.OwnsOne("TrafficForm.Domain.MapViewSnapshot", "View", b1 =>
                        {
                            b1.Property<string>("CoordinateFavoriteFavoriteId")
                                .HasColumnType("text");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<double>("MaxLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("max_latitude");

                            b1.Property<double>("MaxLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("max_longitude");

                            b1.Property<double>("MinLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("min_latitude");

                            b1.Property<double>("MinLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("min_longitude");

                            b1.Property<int>("ZoomLevel")
                                .HasColumnType("integer")
                                .HasColumnName("zoom_level");

                            b1.HasKey("CoordinateFavoriteFavoriteId");

                            b1.ToTable("CoordinateFavorites");

                            b1.WithOwner()
                                .HasForeignKey("CoordinateFavoriteFavoriteId");
                        });

                    b.Navigation("View")
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficForm.Domain.HighwayFavorite", b =>
                {
                    b.OwnsOne("TrafficForm.Domain.MapViewSnapshot", "View", b1 =>
                        {
                            b1.Property<string>("HighwayFavoriteFavoriteId")
                                .HasColumnType("text");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<double>("MaxLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("max_latitude");

                            b1.Property<double>("MaxLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("max_longitude");

                            b1.Property<double>("MinLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("min_latitude");

                            b1.Property<double>("MinLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("min_longitude");

                            b1.Property<int>("ZoomLevel")
                                .HasColumnType("integer")
                                .HasColumnName("zoom_level");

                            b1.HasKey("HighwayFavoriteFavoriteId");

                            b1.ToTable("HighwayFavorites");

                            b1.WithOwner()
                                .HasForeignKey("HighwayFavoriteFavoriteId");
                        });

                    b.Navigation("View")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
